// <auto-generated />
namespace PRScapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addeddatecreatedandchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddatecreatedandchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201803121853583_added date created and changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
